---
title: "Homework 2"
output: html_document
date: "2026-09-25"
---

```{r setup, message=FALSE, warning=FALSE}
library(readr)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
)
```

```{r read-image1}
x <- read_csv("image1.csv", show_col_types = FALSE)
x <- data.matrix(x)

dim(x)
```

```{r plot-helper}
plot_image <- function(x, main = "") {
  
  image(
    1:ncol(x),
    1:nrow(x),
    t(x[nrow(x):1, , drop = FALSE]),
    col = gray.colors(256),
    axes = FALSE,
    xlab = "",
    ylab = "",
    main = main
  )
}
```

```{r original-image}
plot_image(x, "Original Image")
```

```{r compression-function}
compress_image <- function(x, k) {
  
  #  X'X
  V <- crossprod(x)
  
  #eigendecomposition of X'X
  eig <- eigen(V, symmetric = TRUE)
  
  # U eigen vectors
  U <- eig$vectors
  
  #PCS
  Z <- x %*% U
  
  #first k
  U_k <- U[, 1:k, drop = FALSE]
  Z_k <- Z[, 1:k, drop = FALSE]
  x_k <- Z_k %*% t(U_k)
  
  # Frobenius 
  error <- norm(x - x_k, type = "F")
  
  return(list(approximation = x_k,
      error = error))
}
```

```{r test-compression}
result <- compress_image(x, 5)

result$error

plot_image(result$approximation, "Rank 5 approx")
```

```{r first-ten, fig.width=12, fig.height=9}
par(mfrow = c(3, 4), mar = c(1, 1, 3, 1))

plot_image(x, "Original")

for (k in 1:10) {
  
  result <- compress_image(x, k)
  
  plot_image(
    result$approximation,
    paste("k =", k)
  )
}

par(mfrow = c(1, 1))
```

```{r error-calculation}
k_values <- 1:ncol(x)

errors <- sapply(k_values, function(k) {
  compress_image(x, k)$error
})
```

```{r error-plot}
plot(
  k_values,
  errors,
  type = "l",
  lwd = 2,
  xlab = "num of PCs (k)",
  ylab = "frobenius error",
  main = "Approx Error v. k"
)

grid()
```